version: '3'

services:
  php:
    build:
      context: ./php
      args:
        TIMEZONE: Europe/Warsaw
    ports:
      - 80:80
    volumes:
      - ../:/var/www/
    networks:
      - symfony_app
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: autosoftware
      MYSQL_USER: autosoftware
      MYSQL_PASSWORD: autosoftware
    ports:
      - 3306:3306
    networks:
      - symfony_app
networks:
  symfony_app: